### ISSUE TITLE
implement ZCA Whitening

### ISSUE THREAD

**Issue by wsuzume** [hacarus/spm-image#21]
Implement ZCA Whitening with sklearn interface. We want to implement fit and other methods using SVD like PCA implementation as follows.

https://github.com/scikit-learn/scikit-learn/blob/a24c8b46/sklearn/decomposition/pca.py#L107-L564

We should follow same package structure of sklearn like spmimage.decomposition.whitening.py. Within the module, implement WhiteningScaler class.

WhiteningScaler should have 'apply_zca' augment. If apply_zca equals False, WhiteningScaler should just do whitening transformation, not ZCA Whitening, and it acts like PCA implementation of sklearn.

**Comment by wsuzume** [comment]
@tksmd 
There is already small implementation of whitening.py as follows.

https://gist.github.com/wsuzume/51a49eb2e41ab5db4a269da36680724c

 We can use this code in order to implement.

**Comment by tksmd** [comment]
According to the implementation you shared, I think `spmimage.preprocessing.data` should be better to implement. Thoughts ? 

You can refer to some Scaler implementation as follows.

* https://github.com/scikit-learn/scikit-learn/blob/a24c8b46/sklearn/preprocessing/data.py#L461

Aside from it, it looks okay to me. @wsuzume
