### ISSUE TITLE
Parallelizing ADMM

### ISSUE THREAD

**Issue by jakirkham** [hacarus/spm-image#41]
Looking at the [`n_targets` `for`-loop]( https://github.com/hacarus/spm-image/blob/5fb9512592b1ebb38b5f0eb89515da7e6d409133/spmimage/linear_model/admm.py#L86 ), it appears that each `k` can be solved independently from other `k`'s. Given this, it seems like there is a good opportunity to run each `k` in parallel from other `k`s. Combining this with the usage of Cython ( https://github.com/hacarus/spm-image/issues/35 ) and releasing the GIL, it should be possible for this to be embarrassingly parallel.

**Comment by tksmd** [comment]
@jakirkham Thank you for the request. I've implemented parallel execution using joblib and merged in #44.  Close this issue.
