### ISSUE TITLE
Implement TrendFiltering

### ISSUE THREAD

**Issue by sutkss** [hacarus/spm-image#48]
# Issue Description

Implement a class for Trend Filtering inherited from GeneralizedLasso.

* [x] Implement Trend Filtering
* [ ] Example for Trend Filtering

# References

* [l1 Trend Filtering](https://web.stanford.edu/~boyd/papers/pdf/l1_trend_filter.pdf)

**Comment by sutkss** [comment]
Add test case for trend filtering

**Comment by tksmd** [comment]
Merged in #49 and thus closing.
