### ISSUE TITLE
implement KSVD with sklearn interface style

### ISSUE THREAD

**Issue by tksmd** [hacarus/spm-image#6]
Implement KSVD with sklearn interface. You can implement `fit` method and reuse some other method provided by SparceCodingMixin like the following class.

* https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/decomposition/dict_learning.py#L941-L1109

We should follow same package structure of sklearn like `spmimage.decomposition.ksvd.py`. Also implement test code to run KSVD.

**Comment by sutkss** [comment]
ksvdを計算する関数内でOMPの計算をscikit learnのsparce_codingで行っている.
sparse_encodeはjoblibで並列化できるが, 引数をうまく渡せてない.
